import PropTypes from 'prop-types';

const orgAdminPropTypes = {
    formData: PropTypes.shape({
        orgAdminType: PropTypes.number,
        name: PropTypes.string,
        headline: PropTypes.string,
        description: PropTypes.string,
        organizationTypeId: PropTypes.number,
        locationTypeId: PropTypes.number,
        lineOne: PropTypes.string,
        lineTwo: PropTypes.string,
        zip: PropTypes.string,
        stateId: PropTypes.number,
        contactName: PropTypes.string,
        contactPhone: PropTypes.string,
        contactEmail: PropTypes.string,
        isActive: PropTypes.bool,
    }).isRequired,

    values: PropTypes.shape({
        orgAdminType: PropTypes.string,
        name: PropTypes.string,
        headline: PropTypes.string,
        description: PropTypes.string,
        organizationTypeId: PropTypes.string,
        locationTypeId: PropTypes.string,
        lineOne: PropTypes.string,
        lineTwo: PropTypes.string,
        zip: PropTypes.string,
        stateId: PropTypes.string,
        contactName: PropTypes.string,
        contactPhone: PropTypes.string,
        contactEmail: PropTypes.string,
        isActive: PropTypes.bool,
    }).isRequired,

    touched: PropTypes.shape({
        orgAdminType: PropTypes.bool,
        name: PropTypes.bool,
        headline: PropTypes.bool,
        description: PropTypes.bool,
        locationTypeId: PropTypes.bool,
        lineOne: PropTypes.bool,
        lineTwo: PropTypes.bool,
        city: PropTypes.bool,
        zip: PropTypes.bool,
        stateId: PropTypes.bool,
        contactName: PropTypes.bool,
        contactPhone: PropTypes.bool,
        contactEmail: PropTypes.bool,
        isActive: PropTypes.bool,
        createdBy: PropTypes.bool,
        modifiedBy: PropTypes.bool,
    }).isRequired,

    errors: PropTypes.shape({
        orgAdminType: PropTypes.string,
        name: PropTypes.string,
        headline: PropTypes.string,
        description: PropTypes.string,
        locationTypeId: PropTypes.string,
        lineOne: PropTypes.string,
        lineTwo: PropTypes.string,
        city: PropTypes.string,
        zip: PropTypes.string,
        stateId: PropTypes.string,
        contactName: PropTypes.string,
        contactPhone: PropTypes.string,
        contactEmail: PropTypes.string,
        isActive: PropTypes.string,
        createdBy: PropTypes.string,
        modifiedBy: PropTypes.string,
    }).isRequired,

    handleChange: PropTypes.func.isRequired,
    handleBlur: PropTypes.func.isRequired,
    handleSubmit: PropTypes.func.isRequired,
    onChange: PropTypes.func.isRequired,
    nextLabel: PropTypes.string,
    backLabel: PropTypes.string,
    onBack: PropTypes.func.isRequired,
    onNext: PropTypes.func.isRequired,
    isSubmitting: PropTypes.bool.isRequired,
    cantBack: PropTypes.bool.isRequired,
};

export { orgAdminPropTypes };
