import {
    FcFaq,
    FcCalendar,
    FcHome,
    FcGlobe,
    FcIdea,
    FcEngineering,
    FcInfo,
    FcPhone,
    FcShare,
    FcStatistics,
    FcFilingCabinet,
    FcBusiness,
} from 'react-icons/fc';

const MENU_ITEMS = [
    {
        roles: ['Admin'],
        key: 'dashboard',
        label: 'Dashboard',
        isTitle: false,
        icon: FcStatistics,
        url: '/dashboard',
    },
    {
        roles: ['User'],
        key: 'userdashboard',
        label: 'Dashboard',
        isTitle: false,
        icon: FcHome,
        url: 'dash/user',
    },
    {
        roles: ['User', 'Org Admin', 'Admin'],
        key: 'events',
        label: 'Events',
        isTitle: false,
        icon: FcBusiness,
        url: '/events',
    },
    {
        roles: ['User', 'Org Admin', 'Admin'],
        key: 'jobs',
        label: 'Jobs',
        isTitle: false,
        icon: FcEngineering,
        url: '/jobs',
    },
    {
        roles: ['User', 'Org Admin', 'Admin'],
        key: 'blogs',
        label: 'Blogs',
        isTitle: false,
        icon: FcHome,
        url: '/blog',
    },
    {
        roles: ['User', 'Org Admin', 'Admin'],
        key: 'listsharestory',
        label: 'Share Stories',
        isTitle: false,
        icon: FcIdea,
        url: '/sharestory',
    },
    {
        roles: ['Org Admin'],
        key: 'dashboard',
        label: 'Dashboard',
        isTitle: false,
        icon: FcInfo,
        url: '/admin/organization/dashboard',
    },
    {
        roles: ['User'],
        key: 'timesheet',
        label: 'Timesheet',
        isTitle: false,
        icon: FcHome,
        url: '/timesheet/user',
    },
    {
        roles: ['User', 'Org Admin'],
        key: 'contact',
        label: 'Contact',
        isTitle: false,
        icon: FcPhone,
        url: '/contact',
    },
    {
        roles: ['Admin', 'User', 'Org Admin'],
        key: 'faq',
        label: 'FAQ',
        isTitle: false,
        icon: FcFaq,
        url: '/faq',
    },
    {
        roles: ['Admin', 'User', 'Org Admin'],
        key: 'calendar',
        label: 'Schedules',
        isTitle: false,
        icon: FcCalendar,
        url: '/schedules',
    },
    {
        roles: ['Admin', 'User', 'Org Admin'],
        key: 'landing',
        label: 'Landing',
        isTitle: false,
        icon: FcGlobe,
        url: '/',
    },
    {
        roles: ['Admin', 'Org Admin'],
        key: 'surveys',
        label: 'Surveys',
        isTitle: false,
        icon: FcStatistics,
        url: '/admin/surveys',
    },
    {
        roles: ['Admin', 'Org Admin'],
        key: 'resources',
        label: 'Resources',
        isTitle: false,
        icon: FcShare,
        url: '/resources',
    },
    {
        roles: ['Admin'],
        key: 'filemanager',
        label: 'File Manager',
        isTitle: false,
        icon: FcFilingCabinet,
        url: '/filemanager',
    },
];

export default MENU_ITEMS;
