import PropTypes from 'prop-types';

const eventPropTypes = {
    formData: PropTypes.shape({
        eventTypeId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        title: PropTypes.string.isRequired,
        description: PropTypes.string.isRequired,
        imageUrl: PropTypes.string.isRequired,
        organizationId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        locationTypeId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        lineOne: PropTypes.string.isRequired,
        lineTwo: PropTypes.string,
        zip: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        stateId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        latitude: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        longitude: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        isMultiDay: PropTypes.bool.isRequired,
        createdBy: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        modifiedBy: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
    }),

    values: PropTypes.shape({
        eventTypeId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        title: PropTypes.string.isRequired,
        description: PropTypes.string.isRequired,
        imageUrl: PropTypes.string.isRequired,
        organizationId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        locationTypeId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        lineOne: PropTypes.string.isRequired,
        lineTwo: PropTypes.string,
        zip: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        stateId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        latitude: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        longitude: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        isMultiDay: PropTypes.bool.isRequired,
        createdBy: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
        modifiedBy: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
    }),

    touched: PropTypes.shape({
        eventTypeId: PropTypes.bool,
        title: PropTypes.bool,
        description: PropTypes.bool,
        imageUrl: PropTypes.bool,
        organizationId: PropTypes.bool,
        locationTypeId: PropTypes.bool,
        lineOne: PropTypes.bool,
        lineTwo: PropTypes.bool,
        city: PropTypes.bool,
        zip: PropTypes.bool,
        stateId: PropTypes.bool,
        latitude: PropTypes.bool,
        longitude: PropTypes.bool,
        isMultiDay: PropTypes.bool,
        createdBy: PropTypes.bool,
        modifiedBy: PropTypes.bool,
    }),

    errors: PropTypes.shape({
        eventTypeId: PropTypes.string,
        title: PropTypes.string,
        description: PropTypes.string,
        imageUrl: PropTypes.string,
        organizationId: PropTypes.string,
        locationTypeId: PropTypes.string,
        lineOne: PropTypes.string,
        lineTwo: PropTypes.string,
        city: PropTypes.string,
        zip: PropTypes.string,
        stateId: PropTypes.string,
        latitude: PropTypes.string,
        longitude: PropTypes.string,
        isMultiDay: PropTypes.string,
        createdBy: PropTypes.string,
        modifiedBy: PropTypes.string,
    }),

    handleChange: PropTypes.func.isRequired,
    handleBlur: PropTypes.func.isRequired,
    handleSubmit: PropTypes.func.isRequired,
    onChange: PropTypes.func.isRequired,
    nextLabel: PropTypes.string,
    backLabel: PropTypes.string,
    onBack: PropTypes.func.isRequired,
    onNext: PropTypes.func.isRequired,
    isSubmitting: PropTypes.bool.isRequired,
    cantBack: PropTypes.bool.isRequired,
};

export { eventPropTypes };
