# This is a basic workflow to help you get started with Actions

name: CI
env:
  IS_NODE_ENABLED: ${{ true }}
  IS_DOTNET_ENABLED: ${{ true }}
  IS_TESTS_DOTNET_ENABLED: ${{ true }}
  LAUNCH_HTTPS: ${{ false }}
  ENV_TYPE: ${{ 'azure' }}

 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: 
      - master
      - main 
      - Themed-A
      - Themed-B
      - Themed-Xtreme
      - Themed-Architect 
      - Themed-Creative 
      - Themed-Bam 
      - Themed-Carolina
      - Themed-Hyper

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs
  #--------------------------------------------------------------------------------------
  
  DotNet_Job:
    name: DotNet Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set ACTIONS_ALLOW_UNSECURE_COMMANDS variable
        run:  echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=1" >>  $GITHUB_ENV
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 6.0.100
      
      # ----------------------------------------------
      - name: Install dependencies
        working-directory: dotnet
        continue-on-error: false
        if: ${{ env.IS_DOTNET_ENABLED }}
        run: dotnet restore Sabio.Starter.Core.sln
      
      # ----------------------------------------------
      - name: Build
        working-directory: dotnet
        continue-on-error: false
        if: ${{ env.IS_DOTNET_ENABLED }}
        run: dotnet msbuild -warnAsError /property:Configuration=Release /p:RestorePackages=false Sabio.Starter.Core.sln
        
  #--------------------------------------------------------------------------------------
  React_Job:
    name: React Build
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set ACTIONS_ALLOW_UNSECURE_COMMANDS variable
      run:  echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >>  $GITHUB_ENV
          
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      with: 
          node-version: '14.x'

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Code
      uses: actions/checkout@v2.3.4
      continue-on-error: false
        
    - name: Yarn Install Long Time Out
      working-directory: react
      run: yarn install --network-timeout 1000000000

    - name: Yarn Build
      working-directory: react
      run: yarn build