# This is a basic workflow to help you get started with Actions

name: Pull Request Ping
# Controls when the action will run. Triggers the workflow on push or pull request
# see here for diff type of PR event types we can filter to https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
# these types should cover all the use cases we need opened, reopened,closed

on:
  pull_request:
    types: [opened, reopened,closed]
    branches: 
      - master
      - main 
      
jobs:
  printJob:    
    name: Print event
    runs-on: self-hosted
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted,Windows,x64,githubrunner]
    steps:
    - run: |
        echo The PR was merged
      
# jobs:
  # if_merged:
    # if: github.event.pull_request.merged == true
    # runs-on: ubuntu-latest
    # steps:
    # - run: |
      #   echo The PR was merged
